name: CI & Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build WASM package
        run: wasm-pack build --release --target web --out-dir docs/pkg

      - name: Copy web assets
        run: |
          mkdir -p docs
          cp index.html docs/
          cp -R css js static docs/  || echo "no css/js/static dirs"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
